In [14]:
# Lets start by showing the concatenation result 

import torch

X, W_xh = torch.randn(3, 1), torch.randn(1, 4)
H, W_hh = torch.randn(3, 4), torch.randn(4, 4)

print(f"X matrix:\n\n{X}\n\nH matrix:\n\n{H}\n\nW_hx matrix:\n\n{W_xh}\n\nW_hh matrix:\n\n{W_hh}\n\n")

result = torch.matmul(X, W_xh) + torch.matmul(H, W_hh)

concatenation = torch.matmul(torch.cat((X, H), 1), torch.cat((W_xh, W_hh), 0))

print(f"The final result is (X*W_hx + H*W_hh):\n\n{result}\n\n")

print(f"The final result concatenating is (W*z):\n\n{concatenation}\n\n")

if torch.allclose(result, concatenation, atol=1e-8):
    print("Success! Both results are equal! :)")
else:
    print("Tensors are not equal.")



X matrix:

tensor([[1.6009],
        [1.0883],
        [0.7494]])

H matrix:

tensor([[-0.6823, -1.4770, -1.1478,  0.9128],
        [-0.0069, -0.7481, -2.2240, -2.4576],
        [-1.4790, -0.6129, -0.5043, -0.0699]])

W_hx matrix:

tensor([[-1.2122,  1.0336, -0.1706,  0.0522]])

W_hh matrix:

tensor([[ 1.2856, -1.0835,  1.0613, -0.8232],
        [ 0.2025, -1.9428, -0.5447,  1.4693],
        [ 0.6083,  0.5975,  0.6886, -1.3376],
        [-0.4515,  0.7201,  0.9322,  0.8357]])


The final result is (X*W_hx + H*W_hh):

tensor([[-4.2275,  5.2351, -0.1321,  0.7734],
        [-1.7229, -0.5130, -3.6079, -0.1157],
        [-3.2093,  3.2161, -1.7760,  0.9724]])


The final result concatenating is (W*z):

tensor([[-4.2275,  5.2351, -0.1321,  0.7734],
        [-1.7229, -0.5130, -3.6079, -0.1157],
        [-3.2093,  3.2161, -1.7760,  0.9724]])


Success! Both results are equal! :)


### ***A couple questions...***

Why can RNNs express the conditional probability of a token at some time step based on all the previous tokens in the text sequence?

What happens to the gradient if you backpropagate through a long sequence?

We will train this RNN to function as a character-level language model and train it on a corpus consisting of the entire text of H. G. Wells’ The Time Machine. We start by loading the dataset.

In [ ]:
%matplotlib inline
import math
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l